Add a new recipe to run the Sail tests manually via GH Actions
riscv/sail-riscv pull request #229
Opened 2023-03-07 21:26 UTC by rpsene

This PR adds the capability to run the tests manually without depending on a new change to trigger it.

2023-03-07 21:29 UTC, jrtc27 commented
Why? If the model hasn't changed the tests really shouldn't. On the very rare occasion that you need a manual run for some unusual set of circumstances you can just open a dummy PR, but I don't see how this is very useful.

2023-03-07 21:30 UTC, jrtc27 commented
This certainly shouldn't be duplicating so much code if you really do want to add it for some reason. Reuse the existing code and gate steps that are specific to PRs.

2023-03-07 21:30 UTC, jrtc27 requested changes
Unjustified and unnecessarily duplicates code

2023-03-07 21:36 UTC, rpsene commented
@jrtc27 thanks for the feedback, PR changed. Initially I was not doing executing all same steps.

2023-03-07 21:38 UTC, jrtc27 commented on .github/workflows/compile.yml
> +on: [push, pull_request,workflow_dispatch]
```suggestion
on: [push, pull_request, workflow_dispatch]
```
...

2023-03-07 21:48 UTC, rpsene commented on .github/workflows/compile.yml
> +on: [push, pull_request,workflow_dispatch]
fixed in the original PR.

2023-03-14 12:31 UTC, billmcspadden-riscv approved these changes
This looks fine to me.

2023-03-14 12:32 UTC, merged

2023-03-15 00:11 UTC, jrtc27 commented
The minute notes just say "2 use cases" and that this was approved. That is totally useless for anyone not in the meetings. Please justify somewhere, especially when I have explicitly objected to this change and asked for the motivation a week ago.