Add unratified Zacas extension
riscv/sail-riscv pull request #285
Opened 2023-07-15 00:44 UTC by ved-rivos

This PR adds the unratified fast-track Zacas extension that introduces the following instructions:
- amocas.w for RV32 and RV64
- amocas.d for RV32 and RV64
- amocas.q for RV64 only

The specification is here: https://github.com/riscv/riscv-zacas

All current tests pass. New tests for amocas are in this riscv-tests PR: https://github.com/riscv-software-src/riscv-tests/pull/492

2023-08-18 15:38 UTC, jrtc27 commented
> Pull requests should be a single set of related changes with a clean commit history free from merge commits.

-- https://github.com/riscv/sail-riscv/blob/master/CONTRIBUTING.md

2023-08-18 15:39 UTC, jrtc27 requested changes

2023-08-18 15:39 UTC, jrtc27 commented on model/riscv_insts_aext.sail
> +     * For obtaining virtual address, the width is not needed.
No, this breaks things like CHERI that hook ext_data_get_addr. The width *must* be accurate for the access that's about to be performed.

2025-06-27 08:11 UTC, Timmmm commented
I might rebase & update this if that's ok...

2025-06-27 11:18 UTC, ved-rivos commented
Thanks @Timmmm - I did the rebase and keep it fresh a few times over last 2 years but it kept going stale. Thanks for helping rebase it again !

2025-06-27 14:12 UTC, Timmmm commented
I rebased it and reworked it a fair bit (the code has changed a lot!)

I haven't modelled this bit:

> The memory operation performed by an AMOCAS.W/D/Q, when not successful, has acquire semantics if aq bit is 1 **but does not have release semantics, regardless of rl**.

I don't think we can actually model that with the current code, because we tell the memory operations the release semantics before they've told us whether they succeed or not.

I think the correct way to do this would be to have some kind of `release_if_successful` memory ordering, but we don't have that yet. I think we can add it after #792.

Also I haven't tested this version yet.

2025-06-27 14:15 UTC, ved-rivos commented
> Also I haven't tested this version yet.

A set of tests are available [here](https://github.com/riscv-non-isa/riscv-arch-test/tree/dev/riscv-test-suite/rv64i_m/Zacas/src).

2025-06-27 17:58 UTC, arichardson commented on model/riscv_insts_zaamo.sail
> +// AMOCAS.W for RV32 and AMOCAS.Q for RV64 operate on a pair of
```suggestion
// AMOCAS.D for RV32 and AMOCAS.Q for RV64 operate on a pair of
```
I assume this should be a `d`?

2025-06-28 06:06 UTC, jordancarlin commented on model/riscv_types.sail
> +enum amo_word_width = {AMO_BYTE, AMO_HALF, AMO_WORD, AMO_DOUBLE, AMO_QUAD}
Adding `quad` to `word_width` isn’t exclusive to AMOs. I wonder if the approach in #445 would make more sense here.

2025-06-28 09:22 UTC, Timmmm commented on model/riscv_types.sail
> +enum amo_word_width = {AMO_BYTE, AMO_HALF, AMO_WORD, AMO_DOUBLE, AMO_QUAD}
Hmm yeah I wasn't very happy about this either. I think you're right - on balance that approach is better.

The thing I don't like though is that now you can have `QUAD` in instructions that can't ever actually use `QUAD`, `size_enc(QUAD)` isn't detected at compile time, etc. Maybe it's fine?

The other option is to use integers - Sail has much better support for integer types than enums so we could do e.g.

```
type word_width = {1, 2, 4, 8}
type word_width_wide= {1, 2, 4, 8, 16}

mapping size_enc : word_width <-> bits(2) = {
  1 <-> 0b00,
  2 <-> 0b01,
  4 <-> 0b10,
  8 <-> 0b11,
}

mapping size_enc_wide : word_width_wide <-> bits(3) = {
  1 <-> 0b000,
  2 <-> 0b001,
  4 <-> 0b010,
  8 <-> 0b011,
  16 <-> 0b100,
}
```

This would get rid of the need for a separate `size_bytes` mapping.

Thinking about it even more it would probably make even *more* sense to just store the exponent.

```
type width_exp = range(0, 3)
type width_wide_exp = range(0, 4)
```

I think that would provide the best typing and most elegance, though it might be slightly less intuitive?

2025-06-30 15:35 UTC, Timmmm commented on model/riscv_insts_zaamo.sail
> +// AMOCAS.W for RV32 and AMOCAS.Q for RV64 operate on a pair of
Good spot, fixed!

2025-06-30 15:35 UTC, Timmmm commented on model/riscv_types.sail
> +enum amo_word_width = {AMO_BYTE, AMO_HALF, AMO_WORD, AMO_DOUBLE, AMO_QUAD}
Ok I made #1113 to do the first version (not exponents), and then have rebased this PR on top of it. I think it's a lot nicer.

2025-07-01 14:21 UTC, jordancarlin commented on model/riscv_extensions.sail
> +function clause hartSupports(Ext_Zacas) = config extensions.Zacas.supported
Zacas needs to be added to the list later in this file for the device tree.

2025-07-01 14:22 UTC, jordancarlin commented on model/riscv_insts_zaamo.sail
> +function clause currentlyEnabled(Ext_Zacas) = hartSupports(Ext_Zacas) & currentlyEnabled(Ext_Zaamo)
Zacas needs to be given a value above Zaamo in the termination file for Lean.

2025-07-01 15:37 UTC, arichardson commented on model/riscv_insts_zaamo.sail
> +// register. When the first register of a source register pair is
```suggestion
// registers. When the first register of a source register pair is
```

2025-07-01 15:38 UTC, arichardson commented on model/riscv_insts_zaamo.sail
> +overload X_amo = {rX_amo_bits, wX_amo_bits}
Is this the same behaviour as for Zilsd? In that case I'd suggest using something like X_pair() and moving it into a more central file.

2025-07-01 15:40 UTC, Timmmm commented on model/riscv_insts_zaamo.sail
> +overload X_amo = {rX_amo_bits, wX_amo_bits}
Yeah it is. Good idea.

2025-07-02 09:08 UTC, Timmmm commented on model/riscv_extensions.sail
> +function clause hartSupports(Ext_Zacas) = config extensions.Zacas.supported
Done

2025-07-02 09:08 UTC, Timmmm commented on model/riscv_insts_zaamo.sail
> +function clause currentlyEnabled(Ext_Zacas) = hartSupports(Ext_Zacas) & currentlyEnabled(Ext_Zaamo)
Done

2025-07-02 09:26 UTC, Timmmm commented on model/riscv_insts_zaamo.sail
> +overload X_amo = {rX_amo_bits, wX_amo_bits}
Ok I moved it to `riscv_regs.sail`. I also changed it from accepting/returning `width_bytes` and sign-extending to accepting/returning either XLEN or XLEN*2. This means the sign extension is now in the Zacas code, which I think is nicer (also because Zilsd doesn't care about sign extension).

The downside is that the AMO code now has to slice the values it reads... but maybe that's clearer too.

2025-07-07 14:49 UTC, jordancarlin commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
While this might simplify code elsewhere, I'm worried that it will be confusing for a function called `X_pair` to sometimes grab a single register and sometimes grab a pair of registers. I'd be in favor of `X_pair` always returning a pair and pulling the check for whether one or two registers is needed into the calling function so it can decide whether to call `X` or `X_pair`.

2025-07-07 16:11 UTC, Timmmm commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
Maybe a different name would help... I do feel like it makes the code quite a bit simpler. `X_wide`?

2025-07-08 05:41 UTC, jordancarlin commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
Not sure. Also, part of the reason to move this into a more generic file was for Zilsd down the line. I think Zilsd will always access a register pair. At the risk of adding more indirection, what about an `X_wide` function that always accesses a register pair and then an `X_amo` function that has the extra bits needed to conditionally access parts of a register or to call `X_pair`?

2025-07-08 07:58 UTC, Timmmm commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
Yeah but actually `zilsd` `ld` is exactly the same encoding as RV64 `ld`, so with the current definition of `X_pair` they could share exactly the same code. Maybe that is too magical though... It's definitely how I would write it if Sail wasn't meant to be a sort of instructional pseudocode.

2025-07-08 08:45 UTC, arichardson commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
Passing in the width seems a bit odd, it would make more sense to me to do the "do I need a pair of registers" check inside the amocas function and have the `X_pair` unconditionally read/write the pair of registers.

2025-07-08 08:47 UTC, arichardson commented on model/riscv_insts_zaamo.sail
> +                        X_pair(rd, width) = sign_extend(loaded);
```suggestion
                        if width > xlen_bytes then
                          X_pair(rd) = sign_extend(loaded);
                        else
                          X(rd) = sign_extend(loaded);
```

Something like this?

2025-07-08 08:57 UTC, arichardson commented on model/riscv_insts_zaamo.sail
> +          let rs2_val = X_pair(rs2, width)[width * 8 - 1 .. 0];
Wouldn't this be readable as a call to truncate?
```suggestion
          let rs2_val = truncate(if width > xlen_bytes then X_pair(rs2) else X(rs2), width * 8);
```

2025-07-08 12:00 UTC, Timmmm commented on model/riscv_insts_zaamo.sail
> +          let rs2_val = X_pair(rs2, width)[width * 8 - 1 .. 0];
Ah yeah these suggestions seem reasonable to me. I'll update the code.

2025-07-09 10:41 UTC, Timmmm commented on model/riscv_regs.sail
> +val rX_pair_bits : forall 'w, 'w <= xlen_bytes * 2 . (regidx, int('w)) -> bits((if 'w <= xlen_bytes then xlen_bytes else xlen_bytes * 2) * 8)
Ok I updated the code with @arichardson's suggestions. I think it is quite a lot nicer!

2025-07-11 03:09 UTC, jordancarlin commented
Tested this against the Zacas tests in `riscv-arch-test` per https://github.com/riscv/sail-riscv/issues/1133#issuecomment-3058811301 and found a few issues:
- Sail throws a pattern match failure when executing an `amocas` instruction because the `amo_mnemonic` was missing a clause for `AMOCAS`. Seems like the Sail compiler should've caught this one.
- `amocas` instructions are supposed to load the value from memory into rd irrespective of whether or not the swap itself happens. The existing implementation was missing this.

I pushed fixes for both and the `riscv-arch-test` tests pass now.

2025-07-11 10:46 UTC, Timmmm approved these changes
Ah thank you for that!

2025-07-14 08:10 UTC, Timmmm commented
Happy almost 2nd birthday this PR :cake:

2025-07-14 10:31 UTC, merged