Add convenience targets for dual simulator builds
riscv/sail-riscv pull request #310
Opened 2023-09-22 21:45 UTC by rpsene

This commit introduces convenience targets that allow building both simulator binaries with a single command: `make csim_all`.

2023-09-23 00:10 UTC, jrtc27 requested changes
I have a much cleaner version of this in sail-cheri-riscv. I’ll extract it out when I get back next week.

2023-09-25 14:35 UTC, rpsene commented
@jrtc27 what are the issues you see with the changes I have submitted? I would appreciate if you point the problems instead of just sending your version.

2023-09-25 16:52 UTC, jrtc27 commented
It’s targeted at just csim and papers over the mess that is how ARCH is dealt with.

2023-10-10 01:50 UTC, rpsene commented
@jrtc27 as you have not submited your better version I will move forwad with the version I have submited. This is blocking a bunch of other improvements. 

@billmcspadden-riscv  who else can review this?

2023-12-28 02:38 UTC, closed without merging