Assembly for hint instructions needs spaces after mnemonics
riscv/sail-riscv pull request #324
Opened 2023-10-25 01:44 UTC by ThinkOpenly

I admit I'm not quite sure that these assembly representations really define valid mnemonics.

If they do, however, (and maybe regardless) then they certainly seem to need spaces between the mnemonics and the operands, like the assembly representations everywhere else.

2023-10-25 01:58 UTC, jrtc27 commented
It's all a bunch of nonsense; see https://github.com/riscv/sail-riscv/issues/112. If you're touching this code, perhaps you can be persuaded to make the code more sensible and mirror the actual assembly for them?

Note though that this made-up syntax puts a dot at the end of what you've deemed the mnemonic, and so they really do think of the immediate operand as being part of the mnemonic. If you're putting a space after the dot then that just looks even weirder. So either leave them as they are or fix them properly?

2023-10-25 01:59 UTC, jrtc27 requested changes
(see comment)

2023-10-25 13:27 UTC, jjscheel commented
> It's all a bunch of nonsense; see #112. If you're touching this code, perhaps you can be persuaded to make the code more sensible and mirror the actual assembly for them?

@jrtc27, I'm sure @ThinkOpenly would appreciate a more descriptive response that just "nonsense".  While the the link is nice, highlighting the key point would be incredibly helpful not only to Paul but to others trying to learn how to contribute here too.

2023-10-25 14:50 UTC, jrtc27 commented
> > It's all a bunch of nonsense; see #112. If you're touching this code, perhaps you can be persuaded to make the code more sensible and mirror the actual assembly for them?
> 
> @jrtc27, I'm sure @ThinkOpenly would appreciate a more descriptive response that just "nonsense". While the the link is nice, highlighting the key point would be incredibly helpful not only to Paul but to others trying to learn how to contribute here too.

The link *is* the key point. It’s a paragraph that explains the problem.

2023-10-26 00:57 UTC, ThinkOpenly commented
I'm fine moving the discussion to #112. I've just added a comment/question there. I'll close this now.

2023-10-26 00:57 UTC, closed without merging