Add zvbc extension
riscv/sail-riscv pull request #550
Opened 2024-09-15 21:17 UTC by rez5427

2024-09-15 22:31 UTC, jrtc27 commented
Why did you close https://github.com/riscv/sail-riscv/pull/549? Please don't create new PRs when the existing one can be updated just fine...

2024-09-16 07:21 UTC, rez5427 commented
Sorry...

2024-09-16 07:21 UTC, rez5427 commented
> Why did you close #549? Please don't create new PRs when the existing one can be updated just fine...

Sorry...

2024-09-16 10:29 UTC, rez5427 commented
I followed the instructions from the [riscv-vector-tests](https://github.com/chipsalliance/riscv-vector-tests) repository and used the nightly version of the riscv-gnu-toolchain to generate code with the ZVBC extension. I ran six tests from the riscv-vector-tests, all of which successfully passed.
![test](https://github.com/user-attachments/assets/c9ac0766-be45-423a-8f21-1e4d5cb575d1)

2025-03-18 22:46 UTC, nadime15 commented
Hi @rez5427, your PR looks nearly complete. Would you like to rebase your code? Once that’s done, we can review it again.

2025-03-22 07:20 UTC, jordancarlin requested changes
I haven't compared this with the spec yet, but here are some initial comments on the Sail syntax. The extension also needs to be added to the list in the README.

2025-03-22 07:20 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +mapping vm_name : bits(1) <-> string = {
I think you should be able to use the existing `maybe_vmask` function instead of defining this new one. This one also doesn't match the assembly from the isa manual.

2025-03-22 07:20 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +union clause ast = VCLMUL_VV : (bits(1), regidx, regidx, regidx)
These should use `vregidx` for vector register arguments instead of `regidx`.

2025-03-22 07:20 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +  var mask    : vector('n, dec, bool)     = undefined;
I don't think this line is necessary. It should be sufficient to define mask with the let statement below.

2025-03-22 07:20 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +  let vd_val  : vector('n, dec, bits('m)) = read_vreg(num_elem, SEW, LMUL_pow, vd);
```suggestion
  let vd_val  : vector('n, bits('m)) = read_vreg(num_elem, SEW, LMUL_pow, vd);
```

Sail no longer supports different ordering for individual vectors so this is unnecessary.

2025-03-22 07:21 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +union clause ast = VCLMUL_VV : (bits(1), regidx, regidx, regidx)
This one is also why CI is failing.

2025-03-22 07:35 UTC, rez5427 commented on model/riscv_insts_zvbc.sail
> +  <-> 0b001100 @ vm @ encdec_vreg(vs2) @ encdec_reg(rs1) @ 0b110 @ encdec_vreg(vd) @ 0b1010111 if extensionEnabled(Ext_Zvbc)
thanks for noticing

2025-03-22 07:45 UTC, rez5427 commented
I should install sail 0.19

2025-03-22 07:47 UTC, jordancarlin commented on README.md
> +- Zvbc extension for vector carryless multiplication, v1.0
Move this up after Zvbb before Zvkb (and the same in riscv_extensions.sail)

2025-03-22 07:47 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +mapping vm_name : bits(1) <-> string = {
You should be able to delete this function now that you're no longer using it.

2025-03-22 07:47 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +  let vm_val  : bits('n)                  = read_vmask(num_elem, vm, 0b00000);
```suggestion
  let vm_val  : bits('n)                  = read_vmask(num_elem, vm, zvreg);
```

2025-03-24 09:06 UTC, nadime15 reviewed
Okay, I verified the implementation against the vector test suite, and all tests passed successfully.

Besides the formatting, there is just one thing to change for now.

From the spec:
 > These instructions are only defined for SEW=64.

You could add an assert to check for this.

I just noticed that Crypto Vector extensions have dependencies on Zve32x and Zve64x.
In the case of Zvbc, it's Zve64x, but we can ignore this for now.

2025-03-24 10:41 UTC, rez5427 commented
@nadime15 maybe like this `assert(SEW == 64, "Only SEW=64 supported for zvbc");`

2025-03-24 11:23 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +  <-> 0b001100 @ vm @ encdec_vreg(vs2) @ encdec_vreg(vs1) @ 0b010 @ encdec_vreg(vd) @ 0b1010111 when extensionEnabled(Ext_Zvbc)
```suggestion
mapping clause encdec = VCLMUL_VV (vm, vs2, vs1, vd)
  <-> 0b001100 @ vm @ encdec_vreg(vs2) @ encdec_vreg(vs1) @ 0b010 @ encdec_vreg(vd) @ 0b1010111
  when extensionEnabled(Ext_Zvbc)
```

See #809

2025-03-24 11:23 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = true
Either we remove the switch to enable Zvbc or we change it to: 
```suggestion
function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc()
```
Zvbb is also activated by default and does not have a switch. In my opinion, we could remove the switch for Zvbc (`sys_enable_zvbc()`) and keep it set to true.

2025-03-24 12:40 UTC, jordancarlin commented
> @nadime15 maybe like this? `assert(SEW == 64, "Only SEW=64 supported for zvbc");`

It looks like right now this assertion is reachable because there is nothing in the model stopping you from executing this instruction with a different SEW. We want to avoid reachable assertions because they cause the model to stop if they fail.

Since the instruction is only defined for SEW = 64, it would be better to encode this directly in the `encdec` clause so the instruction is not even decoded if SEW is not 64. Something like `when extensionEnabled(Ext_Zvbc) & get_sew() = 64`.

2025-03-25 13:48 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +  vstart = zeros();
```suggestion
  set_vstart(zeros());
```

This ensures V context is dirtied at the end of the instruction. See #816.

2025-03-25 14:09 UTC, nadime15 reviewed
Almost done!

2025-03-25 14:09 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +}
```suggestion
  foreach (i from 0 to (num_elem - 1)) {
    if mask[i] == bitone then {
      foreach (n from 0 to (SEW - 1))
        if vs2_val[i][n] == bitone then result[i] = result[i] ^ (rs1_val << n);
    };
  };
  write_vreg(num_elem, SEW, LMUL_pow, vd, result);
  set_vstart(zeros());
  RETIRE_SUCCESS
}
```

Please do this for each instruction.

2025-03-25 14:09 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +  let vs2_val : vector('n, bits('m)) = read_vreg(num_elem, SEW, LMUL_pow, vs2);
Please fix the formatting for each function as well.

2025-03-25 14:09 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc()
Would it actually make sense for all crypto vector extension to check if the Vector Extension is enabled? I would say so.

@pmundkur, @jordancarlin

2025-03-25 14:25 UTC, rez5427 commented
@nadime15 maybe this is ok

2025-03-25 14:26 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc()
From the spec:
> The Zvknhb and Zvbc Vector Crypto Extensions --and accordingly the composite extensions Zvkn, Zvknc, Zvkng, and Zvksc -- require a Zve64x base, or application ("V") base Vector Extension.
> 
> All of the other Vector Crypto Extensions can be built on any embedded (Zve*) or application ("V") base Vector Extension.

Right now we only have the `V` extension in the model. We need to go through and fix support for all of the other `Zve*` vector extensions (we have the bulk of the code for all of them already, we just need to fix what is enabled when). #785 does a little bit of this. For now, it seems reasonable to have this require `V`, but we'll need to refactor all of the vector extensionEnabled logic soon, so I don't think it's a big deal.

2025-03-25 15:11 UTC, nadime15 approved these changes
Awesome, looks good!

2025-03-25 21:43 UTC, jordancarlin approved these changes
LGTM now!

2025-03-26 21:36 UTC, pmundkur approved these changes

2025-03-26 21:46 UTC, nadime15 commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() & extensionEnabled(Ext_V)
Just one last question, do we want to keep this switch here? I think we could remove it.
@pmundkur, @jordancarlin 
```suggestion
function clause extensionEnabled(Ext_Zvbc) = extensionEnabled(Ext_V)
```

2025-03-26 22:58 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() & extensionEnabled(Ext_V)
I’d say with #758 almost ready to merge, we should avoid adding new command line switches that will be replaced by configuration flags. Either keep `sys_enable_zvbc()` but hardcode it to true or drop it entirely for now.

2025-03-27 10:08 UTC, rez5427 commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() & extensionEnabled(Ext_V)
should I remove all `sys_enable_zvbc` related code?

2025-03-27 12:18 UTC, jordancarlin requested changes

2025-03-27 12:18 UTC, jordancarlin commented on model/riscv_insts_zvbc.sail
> +function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() | extensionEnabled(Ext_V)
```suggestion
function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() & extensionEnabled(Ext_V)
```

2025-03-27 12:18 UTC, jordancarlin commented on c_emulator/riscv_sim.cpp
> +    {"enable-zvbc",                 no_argument,       0, OPT_ENABLE_ZVBC         },
All of the changes in this file should be removed.

2025-03-28 12:22 UTC, pmundkur approved these changes

2025-03-28 13:40 UTC, Timmmm reviewed
Some minor comments, otherwise LGTM.

2025-03-28 13:40 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +      foreach (n from 0 to (SEW - 1))
This should be `from 1 to`. Technically doesn't make a difference since 0 will always result in `result[i] = result[i] ^ 0` but they used 1 in the original pseudocode so it probably makes sense here too.

Ditto for line 148.

2025-03-28 13:40 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +  let 'm = SEW;
Maybe just delete these and the explicit type annotations? Or if we keep the type annotations then don't have two variables for the same thing. You can do

```
let 'n = get_num_elem(...
```

2025-03-28 13:40 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +      foreach (n from 0 to (SEW - 1))
I feel like it would make sense to extract this into `clmul[h]` functions like in the original psuedocode. Easier to test and then it can also be shared with the scalar code.

We could maybe do that in a future PR though.

2025-03-29 16:52 UTC, nibrunie commented
> Okay, I verified the implementation against the vector test suite, and all tests passed successfully.
> 
> Besides the formatting, there is just one thing to change for now.
> 
> From the spec:
> 
> > These instructions are only defined for SEW=64.
> 
> You could add an assert to check for this.
> 
> I just noticed that Crypto Vector extensions have dependencies on Zve32x and Zve64x (which are not implemented yet). In the case of Zvbc, it's Zve64x, but we can ignore this for now.

Shouldn't a comment be added in the code, maybe around
```
function clause extensionEnabled(Ext_Zvbc) = sys_enable_zvbc() & extensionEnabled(Ext_V)
```
to highlight that this will need to be fixed once `Ext_Zve*` are declared to make sure the proper dependency is checked here ?

2025-03-31 14:39 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +      foreach (n from 0 to (SEW - 1))
Will do this in a future PR so the scalar code can use it too.

2025-03-31 14:39 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +  let 'm = SEW;
Apparently all the other vector code is in this style too so leave it for now and we can update them all at once.

2025-03-31 14:41 UTC, Timmmm commented on model/riscv_insts_zvbc.sail
> +      foreach (n from 0 to (SEW - 1))
Just discussed this in the meeting; good to go after this is done.

2025-03-31 15:09 UTC, Timmmm commented
Ah looks like there's a small conflict that needs to be resolved...

2025-03-31 16:00 UTC, merged