Simplify Zicsr AST
riscv/sail-riscv pull request #645
Opened 2024-12-17 18:53 UTC by nwf

Split out from and sitting atop #617, the last commit here is the salient one.  This transforms a `bool * regidx` under one `ast` data constructor into two `ast` data constructors, allowing us to stop punning between `regidx` and `bits(5)`.  This will be significant with  for supporting the E extension, where `regidx` will be (isomorphic to) `bits(4)`.

2024-12-18 12:48 UTC, Timmmm commented
Ah I understand the motivation now. In order to avoid losing the `is_imm` information could we use a union instead?

```
union RegOrImm = {
  Reg : regidx,
  Imm : bits(5),
}
```

2024-12-18 13:22 UTC, nwf commented
I am... reasonably certain we haven't lost any information and that I haven't changed semantics.  Rather than pass in a union and conditionally call `X()`, I just moved the discrimination into `ast` itself and had the appropriate arm unconditionally call `X()`.  Can you say why you think a `union` is beneficial?

2025-01-03 19:57 UTC, arichardson commented on model/riscv_insts_zicsr.sail
> +    _      => unsigned(rs1_val) != 0
I'm not sure this is correct, looking at https://github.com/riscv/riscv-isa-manual/blob/main/src/zicsr.adoc it only says write = false for imm=0 or rs1=0, but if rs1 happens to hold a zero value it still performs the write.

> Note that if rs1 specifies a register other than x0, and that register holds a zero value, the instruction will not action any attendant per-field side effects, but will action any side effects caused by writing to the entire CSR.

2025-01-03 19:58 UTC, arichardson requested changes
I like the split into two separate AST clauses here but I think this changes the behaviour to no longer be correct.

2025-01-03 22:56 UTC, nwf commented on model/riscv_insts_zicsr.sail
> +    _      => unsigned(rs1_val) != 0
Oh, hah, whoops; I was a victim of the kind of type confusion I was hoping to prevent by making things more explicit.

I'll pass `isWrite` to the `doCSR` and have the case arms do the appropriate discrimination.

2025-01-04 01:47 UTC, arichardson approved these changes

2025-01-08 09:40 UTC, Timmmm commented
> Can you say why you think a union is beneficial?

Hey, sorry I forgot to reply to this. There are two cases I know of where knowing `is_imm` is needed:

1. CHERI CLEN CSRs can only have their metadata written CSRRW:

```
function handle_csr_op(csr, rs1, rd, is_imm, op, isWrite, isRead) = {
  if is_clen_csr(csr) then {
    // The only way to write metadata is with `csrrw`.
    // For extended CSRs, it also has to be in CapPtrMode mode.
    // Note `op == CSRRW` means `csrrw` or` csrrwi` which is why we also check `not(is_imm)`.
    let clen_write = (effective_cheri_mode() == CapPtrMode | csr_type(csr) == ClenNew) & op == CSRRW & not(is_imm);
    let write_val = if is_imm then {null_cap with address = zero_extend(rs1)}
      else if clen_write then C(rs1)
      else {null_cap with address = X(rs1)};
...
```

2. Some CLIC CSRs have weird behaviour that depends on `is_imm`. At least `xnxti`:

```
function access_xnxti(
  csr : csreg,
  rs1_val : xlenbits,
  op : csrop,
  is_imm : bool,
  isWrite : bool,
  priv : Privilege) -> xlenbits = {
...
    let min_pil = if is_imm then xcause[Xpil] else rs1_val[23..16];
```

(I haven't upstreamed that code yet; CLIC is a mess and I'm not sure how much we should want it in this repo... but it would be nice if we can still easily add it on.)

Neither of those bits of code are actually in this repo yet though, so maybe it is unfair to worry about them. I guess we could always add `is_imm` back as a parameter to `doCSR` when it is needed?

2025-03-03 22:08 UTC, arichardson commented on model/riscv_insts_zicsr.sail
> +}
is this used anywhere? I don't see it in this commit

2025-03-03 22:13 UTC, arichardson approved these changes
One minor note otherwise LGTM

2025-03-20 17:41 UTC, pmundkur commented
Perhaps modifying the PR is not necessary; github says this can be just merged without conflicts?

2025-03-20 18:38 UTC, arichardson commented
> Perhaps modifying the PR is not necessary; github says this can be just merged without conflicts?

I just clicked the update with rebase button, should now only include the final commit.

2025-03-20 18:57 UTC, nwf commented on model/riscv_insts_zicsr.sail
> +}
No, indeed, looks stale.  I'll remove it.

2025-03-20 20:35 UTC, pmundkur approved these changes

2025-03-20 20:57 UTC, arichardson approved these changes

2025-03-25 14:05 UTC, merged