reflact mstatus handler function
riscv/sail-riscv pull request #652
Opened 2024-12-20 07:06 UTC by KotorinMinami

As mentioned in #639, and there are also some legitimacy issues in legalize_mstatus, so this PR is intended to help make corrections

2025-01-02 10:41 UTC, Timmmm requested changes

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
>    else m.bits[33 .. 32]
```suggestion
  else m[UXL]
```

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +function clause write_CSR((0x310, value) if xlen == 32) = { mstatus.bits[63 .. 32] } // ignore writes for now
```suggestion
function clause write_CSR((0x310, value) if xlen == 32) = { mstatus = legalize_mstatus(mstatus, value @ mstatus.bits[31 .. 0]); mstatus.bits[63 .. 32] }
```

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_vext_regs.sail
> +  if xlen == 32 then mstatus[SD_32] = 0b1
Maybe add a `set_mstatus_sd()` function since there's already a `get` version and you use this twice.

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
>    else m.bits[35 .. 34]
```suggestion
  else m[SXL]
```

I think in future I think we can just use `m[SXL]` directly and initialise it to the RV32 value on RV32: https://github.com/riscv/sail-riscv/pull/597/files#diff-e1a3fe7050c3af4c308a5e39bfb7f0f31094022b9892cee9a611bcb57ccb6726R283

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +    SD_64 = if xlen == 64 then sd else 0b0,
I think I would just do `SD_64 = m[SD_64]` and `SD_32 = m[SD_32]`. The rest of the code should ensure that they don't get set incorrectly.

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_control.sail
> +    UXL = if xlen == 64 then misa[MXL] else mstatus[UXL],
I think just set these to `S/UXL = misa[MXL]`. They are non-reset, and #597 moves the initialisation to a more sensible place so the reset function doesn't have to touch them at all.

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +  let dirty = extStatus_of_bits(m[FS]) == Dirty |
This is subtly incorrect - `XS` is read-only zero but if you write `Dirty` to it you'll still set `SD`. `FS` and `VS` can be read-only zero in some cases too.

I would do it in two stages. First set everything except SD. Then set SD based on the new values.

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +    MDT = m[MDT],
I think we shouldn't add fields and make them writeable if we don't actually support them. I would probably just leave these fields out entirely for now. It's less confusing if we add them when we actually implement their functionality.

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +    VS = m[VS],
Hmm I think we should making `FS` and `VS` read-only zero in some cases. That's an existing bug though - I made an issue: #661

2025-01-02 10:41 UTC, Timmmm commented on model/riscv_sys_regs.sail
> +  let m : Mstatus = Mk_Mstatus(v);
```suggestion
  let m = Mk_Mstatus(v);
```

2025-01-09 09:34 UTC, KotorinMinami commented
@Timmmm Is there anything else that needs improvement in my code?

2025-01-09 10:08 UTC, Timmmm approved these changes
LGTM - would be nice to get a second opinion though. Any takers @arichardson @jordancarlin etc?

2025-01-09 15:30 UTC, arichardson approved these changes
This looks like an improvement to me. Nit: not sure we need to add all the future fields in this PR but I don't mind keeping them here.

2025-01-13 07:20 UTC, jordancarlin approved these changes
Minor nit in a comment but otherwise LGTM

2025-01-13 07:20 UTC, jordancarlin commented on model/riscv_sys_regs.sail
>     * explicitly later.
Comment needs to be updated. All bits are now handled directly in this function.

2025-01-14 05:58 UTC, KotorinMinami commented on model/riscv_sys_regs.sail
>     * explicitly later.
Thanks! I have edited this commit. What do you think of the commit now?

2025-01-14 06:08 UTC, jordancarlin commented on model/riscv_sys_regs.sail
>     * explicitly later.
Seems fine now

2025-01-27 15:58 UTC, merged